# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8dbaec2dd0ff5ba1fd2889c2f6bcbffffc271bcc43a521b5dcf10cea921a56a303cad9564b8fddc8bcd95032ad3e0b559c5e3a308b65c9caf12a36d07dcfc7cd

test:
  secret_key_base: d4703fd01ab7ca8b18b9930a03e39fa23c0572763c13803bbb947ce41ae1fff91e4f5b4ab2782ae71ae37e62ef6831830c463ab3267b35504f5e209711c5b3db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
